EXTRA_OECMAKE = "\
    -DENABLE_PYTHON_API=OFF \
    -DENABLE_PYMOD_UTILS=OFF \
    -DENABLE_SIM=OFF \
    -DENABLE_X400=OFF \
    -DENABLE_N320=OFF \
    -DENABLE_X300=OFF \
    -DENABLE_USRP2=OFF \
    -DENABLE_USRP1=OFF \
    -DENABLE_N300=OFF \
    -DENABLE_E320=OFF \
    -DENABLE_E300=OFF \
    -DPython3_EXECUTABLE=${PYTHON} \

"



-DENABLE_X400=OFF -DENABLE_N320=OFF -DENABLE_X300=OFF -DENABLE_USRP2=OFF -DENABLE_USRP1=OFF -DENABLE_N300=OFF -DENABLE_E320=OFF -DENABLE_E300=OFF 




cmake  -DENABLE_PYTHON_API=OFF  -DENABLE_PYMOD_UTILS=OFF -DENABLE_SIM=OFF -DENABLE_X400=OFF -DENABLE_N320=OFF -DENABLE_X300=OFF -DENABLE_USRP2=OFF -DENABLE_USRP1=OFF -DENABLE_N300=OFF -DENABLE_E320=OFF -DENABLE_E300=OFF  ../



